version: '4'

services:
  apache:
    image: 'php:8.1-apache'
    container_name: php
    restart: always
    ports:
      - '80:80'
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    links:
      - db
  db:
    container_name: mysql
    image: mysql:5.7
    restart: always
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      -  ./SQL/init.sql:/docker-entrypoint-initdb.d/init.sql #executa SQL para criação do banco de dados, tabelas e colunas.